name: build-and-deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: '16'
      GISCUS_REPO: ${{ secrets.GISCUS_REPO }}
      GISCUS_REPO_ID: ${{ secrets.GISCUS_REPO_ID }}
      GISCUS_CATEGORY: ${{ secrets.GISCUS_CATEGORY }}
      GISCUS_CATEGORY_ID: ${{ secrets.GISCUS_CATEGORY_ID }}
      GOOGLE_ANALYTICS: ${{ secrets.GOOGLE_ANALYTICS }}
      BAIDU_ANALYTICS: ${{ secrets.BAIDU_ANALYTICS }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
        env:
          GISCUS_REPO: ${{ env.GISCUS_REPO }}
          GISCUS_REPO_ID: ${{ env.GISCUS_REPO_ID }}
          GISCUS_CATEGORY: ${{ env.GISCUS_CATEGORY }}
          GISCUS_CATEGORY_ID: ${{ env.GISCUS_CATEGORY_ID }}
          GOOGLE_ANALYTICS: ${{ env.GOOGLE_ANALYTICS }}
          BAIDU_ANALYTICS: ${{ env.BAIDU_ANALYTICS }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build site
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: blog/.vuepress/dist
          cname: blog.haydenhayden.com
